- shell:
    - [apt install -y zsh, Installing zsh]
    - ['if [ $SHELL != "/bin/zsh" ]; then chsh -s $(which zsh); fi', Making zsh the default shell]
    - [apt install curl -y, Installing curl]
    - [apt install btop -y, Installing btop]
    - [apt install htop -y, Installing htop]
    - [apt install neofetch -y, Installing neofetch]
