- defaults:
    link:
      force: true

- link:
    ~/.config/krunnerrc: config/krunnerrc
    ~/.config/plasma-org.kde.plasma.desktop-appletsrc: config/plasma-org.kde.plasma.desktop-appletsrc
    ~/.config/plasmarc: config/plasmarc
    ~/.config/kdedefaults: config/kdedefaults
