- defaults:
    link:
      force: true

- link:
    ~/.config/:
      glob: true
      path: config/kde/*

- shell:
  - command: sudo apt-get install kwin-addons -y
    description: Install kwin-addons.
