- shell:
    - command: 'if [ ! -d "$HOME/.oh-my-zsh" ]; then zsh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended; fi'
      description: Installing oh-my-zsh
    - command: curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
      description: Installing zoxide

- link:
    # ZSH
    ~/.zshrc:
      path: zsh/.zshrc
      force: true
    ~/.oh-my-zsh/custom/aliases.zsh:
      path: zsh/omz/custom/aliases.zsh
    ~/.oh-my-zsh/custom/themes/robbyrussell-custom.zsh-theme:
      path: zsh/omz/custom/themes/robbyrussell-custom.zsh-theme
