#!/bin/bash

# Call the color file
. /etc/update-motd.d/colors

# Check updates
n=$(apt-get -qq --just-print dist-upgrade | cut -f 2 -d " " | sort -u | wc -l)
if [[ $n -gt 0 ]]; then
    printf $LIGHT_RED
    printf "  You have %s packages waiting for upgrades." "$n"
    printf $NONE"\n\n"
fi

# Number of unnecessary packages to uninstall
n=$(apt-get -qq --just-print autoremove | cut -f 2 -d " " | sort -u | wc -l)
if [[ $n -gt 0 ]]; then
    printf $YELLOW
    printf "  You have %s packages that were automatically installed and are not needed anymore." "$n"
    printf $NONE"\n\n"
fi
